Makefile.common: abort early if home/exe variables unset or nonexisting
This reduces footgunning by having the makefile abort early if the homes
are wrongly set. Otherwise things go haywire, for instance ending up
with a .vale-depend that looks like this:

	Error in file /home/guido/r/hacl-star/main/vale/code/thirdPartyPorts/OpenSSL/sha/Vale.SHA.PPC64LE.Loop.vaf
	Could not find fst/fsti for dependency Spec.Loops
	Traceback (most recent call last):
	  File "/home/guido/r/hacl-star/main/tools/valedepend.py", line 169, in <module>
	    vale_dependency_scan(norm(vaf))
	  File "/home/guido/r/hacl-star/main/tools/valedepend.py", line 114, in vale_dependency_scan
	    vaf_dump_deps[vaf].add(make_dump(find_fsti(inc)))
					     ^^^^^^^^^^^^^^
	  File "/home/guido/r/hacl-star/main/tools/valedepend.py", line 81, in find_fsti
	    raise Exception('Could not find fst/fsti for dependency ' + module)
	Exception: Could not find fst/fsti for dependency Spec.Loops

valedepend.py should be more defensive itself, but I think a catch-all
at this stage is useful.